maxSpace: 268435456
dep:
  name: test12341234
  key: 5JWUif6MMtT8vMqH7GTQup5sMbkPN93zAaSFejm4nWhDHWtJHQi
miner:
  name: test12341234
  key: 5JWUif6MMtT8vMqH7GTQup5sMbkPN93zAaSFejm4nWhDHWtJHQi
pool:
  name: storePool11
  key: