maxSpace: 10

dep:
  name: username1234
  key: 5JcDH48njDbUQLu1R8SWwKsfWLnqBpWXDDiCgxFC3hioDuwLhVx
miner:
  name: username1234
  key: 5JcDH48njDbUQLu1R8SWwKsfWLnqBpWXDDiCgxFC3hioDuwLhVx
pool:
  name: storepool11
  key: 5JkjKo4UGaTQFVuVpDZDV3LNvLrd2DgGRpTNB4E1o9gVuUf7aYZ

beneficial:
  name: username1234

env:
  - ytfs_path=/Users/mac/YTFS2

snips:
  - 49.234.139.206
  - 129.211.72.15
  - 122.152.203.189
  - 212.129.153.253
  - 49.235.52.30