// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//msgid=0xc487
type NodeCapacityRequest struct {
	RequestMsgID         int32    `protobuf:"varint,1,opt,name=RequestMsgID,proto3" json:"RequestMsgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeCapacityRequest) Reset()         { *m = NodeCapacityRequest{} }
func (m *NodeCapacityRequest) String() string { return proto.CompactTextString(m) }
func (*NodeCapacityRequest) ProtoMessage()    {}
func (*NodeCapacityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *NodeCapacityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeCapacityRequest.Unmarshal(m, b)
}
func (m *NodeCapacityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeCapacityRequest.Marshal(b, m, deterministic)
}
func (m *NodeCapacityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeCapacityRequest.Merge(m, src)
}
func (m *NodeCapacityRequest) XXX_Size() int {
	return xxx_messageInfo_NodeCapacityRequest.Size(m)
}
func (m *NodeCapacityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeCapacityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeCapacityRequest proto.InternalMessageInfo

func (m *NodeCapacityRequest) GetRequestMsgID() int32 {
	if m != nil {
		return m.RequestMsgID
	}
	return 0
}

//msgid=0xe684
type NodeCapacityResponse struct {
	Writable             bool     `protobuf:"varint,1,opt,name=writable,proto3" json:"writable,omitempty"`
	AllocId              string   `protobuf:"bytes,2,opt,name=allocId,proto3" json:"allocId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeCapacityResponse) Reset()         { *m = NodeCapacityResponse{} }
func (m *NodeCapacityResponse) String() string { return proto.CompactTextString(m) }
func (*NodeCapacityResponse) ProtoMessage()    {}
func (*NodeCapacityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *NodeCapacityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeCapacityResponse.Unmarshal(m, b)
}
func (m *NodeCapacityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeCapacityResponse.Marshal(b, m, deterministic)
}
func (m *NodeCapacityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeCapacityResponse.Merge(m, src)
}
func (m *NodeCapacityResponse) XXX_Size() int {
	return xxx_messageInfo_NodeCapacityResponse.Size(m)
}
func (m *NodeCapacityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeCapacityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeCapacityResponse proto.InternalMessageInfo

func (m *NodeCapacityResponse) GetWritable() bool {
	if m != nil {
		return m.Writable
	}
	return false
}

func (m *NodeCapacityResponse) GetAllocId() string {
	if m != nil {
		return m.AllocId
	}
	return ""
}

//msgid=0xCB05
type UploadShardRequest struct {
	SHARDID              int32    `protobuf:"varint,1,opt,name=SHARDID,proto3" json:"SHARDID,omitempty"`
	BPDID                int32    `protobuf:"varint,2,opt,name=BPDID,proto3" json:"BPDID,omitempty"`
	VBI                  int64    `protobuf:"varint,3,opt,name=VBI,proto3" json:"VBI,omitempty"`
	BPDSIGN              []byte   `protobuf:"bytes,4,opt,name=BPDSIGN,proto3" json:"BPDSIGN,omitempty"`
	DAT                  []byte   `protobuf:"bytes,5,opt,name=DAT,proto3" json:"DAT,omitempty"`
	VHF                  []byte   `protobuf:"bytes,6,opt,name=VHF,proto3" json:"VHF,omitempty"`
	USERSIGN             []byte   `protobuf:"bytes,7,opt,name=USERSIGN,proto3" json:"USERSIGN,omitempty"`
	AllocId              string   `protobuf:"bytes,8,opt,name=allocId,proto3" json:"allocId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadShardRequest) Reset()         { *m = UploadShardRequest{} }
func (m *UploadShardRequest) String() string { return proto.CompactTextString(m) }
func (*UploadShardRequest) ProtoMessage()    {}
func (*UploadShardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *UploadShardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadShardRequest.Unmarshal(m, b)
}
func (m *UploadShardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadShardRequest.Marshal(b, m, deterministic)
}
func (m *UploadShardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadShardRequest.Merge(m, src)
}
func (m *UploadShardRequest) XXX_Size() int {
	return xxx_messageInfo_UploadShardRequest.Size(m)
}
func (m *UploadShardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadShardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadShardRequest proto.InternalMessageInfo

func (m *UploadShardRequest) GetSHARDID() int32 {
	if m != nil {
		return m.SHARDID
	}
	return 0
}

func (m *UploadShardRequest) GetBPDID() int32 {
	if m != nil {
		return m.BPDID
	}
	return 0
}

func (m *UploadShardRequest) GetVBI() int64 {
	if m != nil {
		return m.VBI
	}
	return 0
}

func (m *UploadShardRequest) GetBPDSIGN() []byte {
	if m != nil {
		return m.BPDSIGN
	}
	return nil
}

func (m *UploadShardRequest) GetDAT() []byte {
	if m != nil {
		return m.DAT
	}
	return nil
}

func (m *UploadShardRequest) GetVHF() []byte {
	if m != nil {
		return m.VHF
	}
	return nil
}

func (m *UploadShardRequest) GetUSERSIGN() []byte {
	if m != nil {
		return m.USERSIGN
	}
	return nil
}

func (m *UploadShardRequest) GetAllocId() string {
	if m != nil {
		return m.AllocId
	}
	return ""
}

type UploadShardResponse struct {
	RES                  int32    `protobuf:"varint,1,opt,name=RES,proto3" json:"RES,omitempty"`
	SHARDID              int32    `protobuf:"varint,2,opt,name=SHARDID,proto3" json:"SHARDID,omitempty"`
	VBI                  int64    `protobuf:"varint,3,opt,name=VBI,proto3" json:"VBI,omitempty"`
	VHF                  []byte   `protobuf:"bytes,4,opt,name=VHF,proto3" json:"VHF,omitempty"`
	USERSIGN             []byte   `protobuf:"bytes,5,opt,name=USERSIGN,proto3" json:"USERSIGN,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadShardResponse) Reset()         { *m = UploadShardResponse{} }
func (m *UploadShardResponse) String() string { return proto.CompactTextString(m) }
func (*UploadShardResponse) ProtoMessage()    {}
func (*UploadShardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *UploadShardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadShardResponse.Unmarshal(m, b)
}
func (m *UploadShardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadShardResponse.Marshal(b, m, deterministic)
}
func (m *UploadShardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadShardResponse.Merge(m, src)
}
func (m *UploadShardResponse) XXX_Size() int {
	return xxx_messageInfo_UploadShardResponse.Size(m)
}
func (m *UploadShardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadShardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadShardResponse proto.InternalMessageInfo

func (m *UploadShardResponse) GetRES() int32 {
	if m != nil {
		return m.RES
	}
	return 0
}

func (m *UploadShardResponse) GetSHARDID() int32 {
	if m != nil {
		return m.SHARDID
	}
	return 0
}

func (m *UploadShardResponse) GetVBI() int64 {
	if m != nil {
		return m.VBI
	}
	return 0
}

func (m *UploadShardResponse) GetVHF() []byte {
	if m != nil {
		return m.VHF
	}
	return nil
}

func (m *UploadShardResponse) GetUSERSIGN() []byte {
	if m != nil {
		return m.USERSIGN
	}
	return nil
}

type UploadShard2CResponse struct {
	RES                  int32    `protobuf:"varint,1,opt,name=RES,proto3" json:"RES,omitempty"`
	DNSIGN               string   `protobuf:"bytes,2,opt,name=DNSIGN,proto3" json:"DNSIGN,omitempty"`
	Seq                  int64    `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Hash                 []byte   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadShard2CResponse) Reset()         { *m = UploadShard2CResponse{} }
func (m *UploadShard2CResponse) String() string { return proto.CompactTextString(m) }
func (*UploadShard2CResponse) ProtoMessage()    {}
func (*UploadShard2CResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *UploadShard2CResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadShard2CResponse.Unmarshal(m, b)
}
func (m *UploadShard2CResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadShard2CResponse.Marshal(b, m, deterministic)
}
func (m *UploadShard2CResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadShard2CResponse.Merge(m, src)
}
func (m *UploadShard2CResponse) XXX_Size() int {
	return xxx_messageInfo_UploadShard2CResponse.Size(m)
}
func (m *UploadShard2CResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadShard2CResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadShard2CResponse proto.InternalMessageInfo

func (m *UploadShard2CResponse) GetRES() int32 {
	if m != nil {
		return m.RES
	}
	return 0
}

func (m *UploadShard2CResponse) GetDNSIGN() string {
	if m != nil {
		return m.DNSIGN
	}
	return ""
}

func (m *UploadShard2CResponse) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *UploadShard2CResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type DownloadShardRequest struct {
	VHF                  []byte   `protobuf:"bytes,1,opt,name=VHF,proto3" json:"VHF,omitempty"`
	AllocId              string   `protobuf:"bytes,2,opt,name=allocId,proto3" json:"allocId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadShardRequest) Reset()         { *m = DownloadShardRequest{} }
func (m *DownloadShardRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadShardRequest) ProtoMessage()    {}
func (*DownloadShardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *DownloadShardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadShardRequest.Unmarshal(m, b)
}
func (m *DownloadShardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadShardRequest.Marshal(b, m, deterministic)
}
func (m *DownloadShardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadShardRequest.Merge(m, src)
}
func (m *DownloadShardRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadShardRequest.Size(m)
}
func (m *DownloadShardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadShardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadShardRequest proto.InternalMessageInfo

func (m *DownloadShardRequest) GetVHF() []byte {
	if m != nil {
		return m.VHF
	}
	return nil
}

func (m *DownloadShardRequest) GetAllocId() string {
	if m != nil {
		return m.AllocId
	}
	return ""
}

type DownloadShardResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadShardResponse) Reset()         { *m = DownloadShardResponse{} }
func (m *DownloadShardResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadShardResponse) ProtoMessage()    {}
func (*DownloadShardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *DownloadShardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadShardResponse.Unmarshal(m, b)
}
func (m *DownloadShardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadShardResponse.Marshal(b, m, deterministic)
}
func (m *DownloadShardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadShardResponse.Merge(m, src)
}
func (m *DownloadShardResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadShardResponse.Size(m)
}
func (m *DownloadShardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadShardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadShardResponse proto.InternalMessageInfo

func (m *DownloadShardResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type NodeRegReq struct {
	Nodeid               string   `protobuf:"bytes,1,opt,name=nodeid,proto3" json:"nodeid,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	MaxDataSpace         uint64   `protobuf:"varint,3,opt,name=maxDataSpace,proto3" json:"maxDataSpace,omitempty"`
	Addrs                []string `protobuf:"bytes,4,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Relay                bool     `protobuf:"varint,5,opt,name=relay,proto3" json:"relay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeRegReq) Reset()         { *m = NodeRegReq{} }
func (m *NodeRegReq) String() string { return proto.CompactTextString(m) }
func (*NodeRegReq) ProtoMessage()    {}
func (*NodeRegReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *NodeRegReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRegReq.Unmarshal(m, b)
}
func (m *NodeRegReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRegReq.Marshal(b, m, deterministic)
}
func (m *NodeRegReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRegReq.Merge(m, src)
}
func (m *NodeRegReq) XXX_Size() int {
	return xxx_messageInfo_NodeRegReq.Size(m)
}
func (m *NodeRegReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRegReq.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRegReq proto.InternalMessageInfo

func (m *NodeRegReq) GetNodeid() string {
	if m != nil {
		return m.Nodeid
	}
	return ""
}

func (m *NodeRegReq) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *NodeRegReq) GetMaxDataSpace() uint64 {
	if m != nil {
		return m.MaxDataSpace
	}
	return 0
}

func (m *NodeRegReq) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func (m *NodeRegReq) GetRelay() bool {
	if m != nil {
		return m.Relay
	}
	return false
}

type NodeRegResp struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AssignedSpace        uint64   `protobuf:"varint,2,opt,name=assignedSpace,proto3" json:"assignedSpace,omitempty"`
	RelayUrl             string   `protobuf:"bytes,3,opt,name=relayUrl,proto3" json:"relayUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeRegResp) Reset()         { *m = NodeRegResp{} }
func (m *NodeRegResp) String() string { return proto.CompactTextString(m) }
func (*NodeRegResp) ProtoMessage()    {}
func (*NodeRegResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *NodeRegResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRegResp.Unmarshal(m, b)
}
func (m *NodeRegResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRegResp.Marshal(b, m, deterministic)
}
func (m *NodeRegResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRegResp.Merge(m, src)
}
func (m *NodeRegResp) XXX_Size() int {
	return xxx_messageInfo_NodeRegResp.Size(m)
}
func (m *NodeRegResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRegResp.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRegResp proto.InternalMessageInfo

func (m *NodeRegResp) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NodeRegResp) GetAssignedSpace() uint64 {
	if m != nil {
		return m.AssignedSpace
	}
	return 0
}

func (m *NodeRegResp) GetRelayUrl() string {
	if m != nil {
		return m.RelayUrl
	}
	return ""
}

type StatusRepReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cpu                  uint32   `protobuf:"varint,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory               uint32   `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Bandwidth            uint32   `protobuf:"varint,4,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	MaxDataSpace         uint64   `protobuf:"varint,5,opt,name=maxDataSpace,proto3" json:"maxDataSpace,omitempty"`
	AssignedSpace        uint64   `protobuf:"varint,6,opt,name=assignedSpace,proto3" json:"assignedSpace,omitempty"`
	UsedSpace            uint64   `protobuf:"varint,7,opt,name=usedSpace,proto3" json:"usedSpace,omitempty"`
	Addrs                []string `protobuf:"bytes,8,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Relay                bool     `protobuf:"varint,9,opt,name=relay,proto3" json:"relay,omitempty"`
	Version              uint32   `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	Rebuilding           uint32   `protobuf:"varint,11,opt,name=rebuilding,proto3" json:"rebuilding,omitempty"`
	RealSpace            uint32   `protobuf:"varint,12,opt,name=realSpace,proto3" json:"realSpace,omitempty"`
	Tx                   uint64   `protobuf:"varint,13,opt,name=tx,proto3" json:"tx,omitempty"`
	Rx                   uint64   `protobuf:"varint,14,opt,name=rx,proto3" json:"rx,omitempty"`
	Other                string   `protobuf:"bytes,15,opt,name=Other,proto3" json:"Other,omitempty"`
	Hash                 string   `protobuf:"bytes,16,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRepReq) Reset()         { *m = StatusRepReq{} }
func (m *StatusRepReq) String() string { return proto.CompactTextString(m) }
func (*StatusRepReq) ProtoMessage()    {}
func (*StatusRepReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *StatusRepReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRepReq.Unmarshal(m, b)
}
func (m *StatusRepReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRepReq.Marshal(b, m, deterministic)
}
func (m *StatusRepReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRepReq.Merge(m, src)
}
func (m *StatusRepReq) XXX_Size() int {
	return xxx_messageInfo_StatusRepReq.Size(m)
}
func (m *StatusRepReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRepReq.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRepReq proto.InternalMessageInfo

func (m *StatusRepReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StatusRepReq) GetCpu() uint32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *StatusRepReq) GetMemory() uint32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *StatusRepReq) GetBandwidth() uint32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

func (m *StatusRepReq) GetMaxDataSpace() uint64 {
	if m != nil {
		return m.MaxDataSpace
	}
	return 0
}

func (m *StatusRepReq) GetAssignedSpace() uint64 {
	if m != nil {
		return m.AssignedSpace
	}
	return 0
}

func (m *StatusRepReq) GetUsedSpace() uint64 {
	if m != nil {
		return m.UsedSpace
	}
	return 0
}

func (m *StatusRepReq) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func (m *StatusRepReq) GetRelay() bool {
	if m != nil {
		return m.Relay
	}
	return false
}

func (m *StatusRepReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *StatusRepReq) GetRebuilding() uint32 {
	if m != nil {
		return m.Rebuilding
	}
	return 0
}

func (m *StatusRepReq) GetRealSpace() uint32 {
	if m != nil {
		return m.RealSpace
	}
	return 0
}

func (m *StatusRepReq) GetTx() uint64 {
	if m != nil {
		return m.Tx
	}
	return 0
}

func (m *StatusRepReq) GetRx() uint64 {
	if m != nil {
		return m.Rx
	}
	return 0
}

func (m *StatusRepReq) GetOther() string {
	if m != nil {
		return m.Other
	}
	return ""
}

func (m *StatusRepReq) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type StatusRepResp struct {
	ProductiveSpace      int64    `protobuf:"varint,1,opt,name=productiveSpace,proto3" json:"productiveSpace,omitempty"`
	RelayUrl             string   `protobuf:"bytes,2,opt,name=relayUrl,proto3" json:"relayUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRepResp) Reset()         { *m = StatusRepResp{} }
func (m *StatusRepResp) String() string { return proto.CompactTextString(m) }
func (*StatusRepResp) ProtoMessage()    {}
func (*StatusRepResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *StatusRepResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRepResp.Unmarshal(m, b)
}
func (m *StatusRepResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRepResp.Marshal(b, m, deterministic)
}
func (m *StatusRepResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRepResp.Merge(m, src)
}
func (m *StatusRepResp) XXX_Size() int {
	return xxx_messageInfo_StatusRepResp.Size(m)
}
func (m *StatusRepResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRepResp.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRepResp proto.InternalMessageInfo

func (m *StatusRepResp) GetProductiveSpace() int64 {
	if m != nil {
		return m.ProductiveSpace
	}
	return 0
}

func (m *StatusRepResp) GetRelayUrl() string {
	if m != nil {
		return m.RelayUrl
	}
	return ""
}

type ErrorMessage struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorMessage) Reset()         { *m = ErrorMessage{} }
func (m *ErrorMessage) String() string { return proto.CompactTextString(m) }
func (*ErrorMessage) ProtoMessage()    {}
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *ErrorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorMessage.Unmarshal(m, b)
}
func (m *ErrorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorMessage.Marshal(b, m, deterministic)
}
func (m *ErrorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorMessage.Merge(m, src)
}
func (m *ErrorMessage) XXX_Size() int {
	return xxx_messageInfo_ErrorMessage.Size(m)
}
func (m *ErrorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorMessage proto.InternalMessageInfo

func (m *ErrorMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ErrorMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StringMsg struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMsg) Reset()         { *m = StringMsg{} }
func (m *StringMsg) String() string { return proto.CompactTextString(m) }
func (*StringMsg) ProtoMessage()    {}
func (*StringMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}

func (m *StringMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMsg.Unmarshal(m, b)
}
func (m *StringMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMsg.Marshal(b, m, deterministic)
}
func (m *StringMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMsg.Merge(m, src)
}
func (m *StringMsg) XXX_Size() int {
	return xxx_messageInfo_StringMsg.Size(m)
}
func (m *StringMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMsg.DiscardUnknown(m)
}

var xxx_messageInfo_StringMsg proto.InternalMessageInfo

func (m *StringMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SpotCheckTaskList struct {
	TaskId               string           `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Snid                 int32            `protobuf:"varint,2,opt,name=snid,proto3" json:"snid,omitempty"`
	TaskList             []*SpotCheckTask `protobuf:"bytes,3,rep,name=taskList,proto3" json:"taskList,omitempty"`
	AllocId              string           `protobuf:"bytes,4,opt,name=allocId,proto3" json:"allocId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SpotCheckTaskList) Reset()         { *m = SpotCheckTaskList{} }
func (m *SpotCheckTaskList) String() string { return proto.CompactTextString(m) }
func (*SpotCheckTaskList) ProtoMessage()    {}
func (*SpotCheckTaskList) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13}
}

func (m *SpotCheckTaskList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotCheckTaskList.Unmarshal(m, b)
}
func (m *SpotCheckTaskList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotCheckTaskList.Marshal(b, m, deterministic)
}
func (m *SpotCheckTaskList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotCheckTaskList.Merge(m, src)
}
func (m *SpotCheckTaskList) XXX_Size() int {
	return xxx_messageInfo_SpotCheckTaskList.Size(m)
}
func (m *SpotCheckTaskList) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotCheckTaskList.DiscardUnknown(m)
}

var xxx_messageInfo_SpotCheckTaskList proto.InternalMessageInfo

func (m *SpotCheckTaskList) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *SpotCheckTaskList) GetSnid() int32 {
	if m != nil {
		return m.Snid
	}
	return 0
}

func (m *SpotCheckTaskList) GetTaskList() []*SpotCheckTask {
	if m != nil {
		return m.TaskList
	}
	return nil
}

func (m *SpotCheckTaskList) GetAllocId() string {
	if m != nil {
		return m.AllocId
	}
	return ""
}

type SpotCheckTask struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Addr                 string   `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	VHF                  []byte   `protobuf:"bytes,4,opt,name=VHF,proto3" json:"VHF,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotCheckTask) Reset()         { *m = SpotCheckTask{} }
func (m *SpotCheckTask) String() string { return proto.CompactTextString(m) }
func (*SpotCheckTask) ProtoMessage()    {}
func (*SpotCheckTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{14}
}

func (m *SpotCheckTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotCheckTask.Unmarshal(m, b)
}
func (m *SpotCheckTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotCheckTask.Marshal(b, m, deterministic)
}
func (m *SpotCheckTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotCheckTask.Merge(m, src)
}
func (m *SpotCheckTask) XXX_Size() int {
	return xxx_messageInfo_SpotCheckTask.Size(m)
}
func (m *SpotCheckTask) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotCheckTask.DiscardUnknown(m)
}

var xxx_messageInfo_SpotCheckTask proto.InternalMessageInfo

func (m *SpotCheckTask) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SpotCheckTask) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *SpotCheckTask) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *SpotCheckTask) GetVHF() []byte {
	if m != nil {
		return m.VHF
	}
	return nil
}

type SpotCheckStatus struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	InvalidNodeList      []int32  `protobuf:"varint,2,rep,packed,name=invalidNodeList,proto3" json:"invalidNodeList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotCheckStatus) Reset()         { *m = SpotCheckStatus{} }
func (m *SpotCheckStatus) String() string { return proto.CompactTextString(m) }
func (*SpotCheckStatus) ProtoMessage()    {}
func (*SpotCheckStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{15}
}

func (m *SpotCheckStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotCheckStatus.Unmarshal(m, b)
}
func (m *SpotCheckStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotCheckStatus.Marshal(b, m, deterministic)
}
func (m *SpotCheckStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotCheckStatus.Merge(m, src)
}
func (m *SpotCheckStatus) XXX_Size() int {
	return xxx_messageInfo_SpotCheckStatus.Size(m)
}
func (m *SpotCheckStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotCheckStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SpotCheckStatus proto.InternalMessageInfo

func (m *SpotCheckStatus) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *SpotCheckStatus) GetInvalidNodeList() []int32 {
	if m != nil {
		return m.InvalidNodeList
	}
	return nil
}

//RS编码重建任务
//msgid=0xd761
type TaskDescription struct {
	Id                   []byte         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hashs                [][]byte       `protobuf:"bytes,2,rep,name=hashs,proto3" json:"hashs,omitempty"`
	Locations            []*P2PLocation `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	ParityShardCount     int32          `protobuf:"varint,4,opt,name=parityShardCount,proto3" json:"parityShardCount,omitempty"`
	RecoverId            int32          `protobuf:"varint,5,opt,name=recoverId,proto3" json:"recoverId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TaskDescription) Reset()         { *m = TaskDescription{} }
func (m *TaskDescription) String() string { return proto.CompactTextString(m) }
func (*TaskDescription) ProtoMessage()    {}
func (*TaskDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{16}
}

func (m *TaskDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDescription.Unmarshal(m, b)
}
func (m *TaskDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDescription.Marshal(b, m, deterministic)
}
func (m *TaskDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDescription.Merge(m, src)
}
func (m *TaskDescription) XXX_Size() int {
	return xxx_messageInfo_TaskDescription.Size(m)
}
func (m *TaskDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDescription.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDescription proto.InternalMessageInfo

func (m *TaskDescription) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *TaskDescription) GetHashs() [][]byte {
	if m != nil {
		return m.Hashs
	}
	return nil
}

func (m *TaskDescription) GetLocations() []*P2PLocation {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *TaskDescription) GetParityShardCount() int32 {
	if m != nil {
		return m.ParityShardCount
	}
	return 0
}

func (m *TaskDescription) GetRecoverId() int32 {
	if m != nil {
		return m.RecoverId
	}
	return 0
}

//msgid=0xc258
type TaskDescriptionCP struct {
	Id                   []byte         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DataHash             []byte         `protobuf:"bytes,2,opt,name=dataHash,proto3" json:"dataHash,omitempty"`
	Locations            []*P2PLocation `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TaskDescriptionCP) Reset()         { *m = TaskDescriptionCP{} }
func (m *TaskDescriptionCP) String() string { return proto.CompactTextString(m) }
func (*TaskDescriptionCP) ProtoMessage()    {}
func (*TaskDescriptionCP) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{17}
}

func (m *TaskDescriptionCP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDescriptionCP.Unmarshal(m, b)
}
func (m *TaskDescriptionCP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDescriptionCP.Marshal(b, m, deterministic)
}
func (m *TaskDescriptionCP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDescriptionCP.Merge(m, src)
}
func (m *TaskDescriptionCP) XXX_Size() int {
	return xxx_messageInfo_TaskDescriptionCP.Size(m)
}
func (m *TaskDescriptionCP) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDescriptionCP.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDescriptionCP proto.InternalMessageInfo

func (m *TaskDescriptionCP) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *TaskDescriptionCP) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

func (m *TaskDescriptionCP) GetLocations() []*P2PLocation {
	if m != nil {
		return m.Locations
	}
	return nil
}

type P2PLocation struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Addrs                []string `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P2PLocation) Reset()         { *m = P2PLocation{} }
func (m *P2PLocation) String() string { return proto.CompactTextString(m) }
func (*P2PLocation) ProtoMessage()    {}
func (*P2PLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{18}
}

func (m *P2PLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P2PLocation.Unmarshal(m, b)
}
func (m *P2PLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P2PLocation.Marshal(b, m, deterministic)
}
func (m *P2PLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PLocation.Merge(m, src)
}
func (m *P2PLocation) XXX_Size() int {
	return xxx_messageInfo_P2PLocation.Size(m)
}
func (m *P2PLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PLocation.DiscardUnknown(m)
}

var xxx_messageInfo_P2PLocation proto.InternalMessageInfo

func (m *P2PLocation) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *P2PLocation) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

//矿机收到任务请回复VoidResp
//msgid=0xe64f
type VoidResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoidResponse) Reset()         { *m = VoidResponse{} }
func (m *VoidResponse) String() string { return proto.CompactTextString(m) }
func (*VoidResponse) ProtoMessage()    {}
func (*VoidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{19}
}

func (m *VoidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoidResponse.Unmarshal(m, b)
}
func (m *VoidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoidResponse.Marshal(b, m, deterministic)
}
func (m *VoidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoidResponse.Merge(m, src)
}
func (m *VoidResponse) XXX_Size() int {
	return xxx_messageInfo_VoidResponse.Size(m)
}
func (m *VoidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VoidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VoidResponse proto.InternalMessageInfo

//矿机重建完毕后向任务发起方SN返回结果
//msgid=0x16f3
type TaskOpResult struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RES                  int32    `protobuf:"varint,2,opt,name=RES,proto3" json:"RES,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskOpResult) Reset()         { *m = TaskOpResult{} }
func (m *TaskOpResult) String() string { return proto.CompactTextString(m) }
func (*TaskOpResult) ProtoMessage()    {}
func (*TaskOpResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{20}
}

func (m *TaskOpResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskOpResult.Unmarshal(m, b)
}
func (m *TaskOpResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskOpResult.Marshal(b, m, deterministic)
}
func (m *TaskOpResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskOpResult.Merge(m, src)
}
func (m *TaskOpResult) XXX_Size() int {
	return xxx_messageInfo_TaskOpResult.Size(m)
}
func (m *TaskOpResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskOpResult.DiscardUnknown(m)
}

var xxx_messageInfo_TaskOpResult proto.InternalMessageInfo

func (m *TaskOpResult) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *TaskOpResult) GetRES() int32 {
	if m != nil {
		return m.RES
	}
	return 0
}

//MessageID:2cb0
type MultiTaskDescription struct {
	Tasklist             [][]byte `protobuf:"bytes,1,rep,name=tasklist,proto3" json:"tasklist,omitempty"`
	ExpiredTime          int64    `protobuf:"varint,2,opt,name=expiredTime,proto3" json:"expiredTime,omitempty"`
	SrcNodeID            int32    `protobuf:"varint,3,opt,name=srcNodeID,proto3" json:"srcNodeID,omitempty"`
	ExpiredTimeGap       int32    `protobuf:"varint,4,opt,name=expiredTimeGap,proto3" json:"expiredTimeGap,omitempty"`
	AllocId              string   `protobuf:"bytes,5,opt,name=allocId,proto3" json:"allocId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiTaskDescription) Reset()         { *m = MultiTaskDescription{} }
func (m *MultiTaskDescription) String() string { return proto.CompactTextString(m) }
func (*MultiTaskDescription) ProtoMessage()    {}
func (*MultiTaskDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{21}
}

func (m *MultiTaskDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiTaskDescription.Unmarshal(m, b)
}
func (m *MultiTaskDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiTaskDescription.Marshal(b, m, deterministic)
}
func (m *MultiTaskDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiTaskDescription.Merge(m, src)
}
func (m *MultiTaskDescription) XXX_Size() int {
	return xxx_messageInfo_MultiTaskDescription.Size(m)
}
func (m *MultiTaskDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiTaskDescription.DiscardUnknown(m)
}

var xxx_messageInfo_MultiTaskDescription proto.InternalMessageInfo

func (m *MultiTaskDescription) GetTasklist() [][]byte {
	if m != nil {
		return m.Tasklist
	}
	return nil
}

func (m *MultiTaskDescription) GetExpiredTime() int64 {
	if m != nil {
		return m.ExpiredTime
	}
	return 0
}

func (m *MultiTaskDescription) GetSrcNodeID() int32 {
	if m != nil {
		return m.SrcNodeID
	}
	return 0
}

func (m *MultiTaskDescription) GetExpiredTimeGap() int32 {
	if m != nil {
		return m.ExpiredTimeGap
	}
	return 0
}

func (m *MultiTaskDescription) GetAllocId() string {
	if m != nil {
		return m.AllocId
	}
	return ""
}

//MessageID:1b31
type MultiTaskOpResult struct {
	Id                   [][]byte `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	RES                  []int32  `protobuf:"varint,2,rep,packed,name=RES,proto3" json:"RES,omitempty"`
	NodeID               int32    `protobuf:"varint,3,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	ExpiredTime          int64    `protobuf:"varint,4,opt,name=expiredTime,proto3" json:"expiredTime,omitempty"`
	SrcNodeID            int32    `protobuf:"varint,5,opt,name=srcNodeID,proto3" json:"srcNodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiTaskOpResult) Reset()         { *m = MultiTaskOpResult{} }
func (m *MultiTaskOpResult) String() string { return proto.CompactTextString(m) }
func (*MultiTaskOpResult) ProtoMessage()    {}
func (*MultiTaskOpResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{22}
}

func (m *MultiTaskOpResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiTaskOpResult.Unmarshal(m, b)
}
func (m *MultiTaskOpResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiTaskOpResult.Marshal(b, m, deterministic)
}
func (m *MultiTaskOpResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiTaskOpResult.Merge(m, src)
}
func (m *MultiTaskOpResult) XXX_Size() int {
	return xxx_messageInfo_MultiTaskOpResult.Size(m)
}
func (m *MultiTaskOpResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiTaskOpResult.DiscardUnknown(m)
}

var xxx_messageInfo_MultiTaskOpResult proto.InternalMessageInfo

func (m *MultiTaskOpResult) GetId() [][]byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *MultiTaskOpResult) GetRES() []int32 {
	if m != nil {
		return m.RES
	}
	return nil
}

func (m *MultiTaskOpResult) GetNodeID() int32 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *MultiTaskOpResult) GetExpiredTime() int64 {
	if m != nil {
		return m.ExpiredTime
	}
	return 0
}

func (m *MultiTaskOpResult) GetSrcNodeID() int32 {
	if m != nil {
		return m.SrcNodeID
	}
	return 0
}

//MessageID:93e4
type MultiTaskOpResultRes struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	SuccNum              int32    `protobuf:"varint,2,opt,name=SuccNum,proto3" json:"SuccNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiTaskOpResultRes) Reset()         { *m = MultiTaskOpResultRes{} }
func (m *MultiTaskOpResultRes) String() string { return proto.CompactTextString(m) }
func (*MultiTaskOpResultRes) ProtoMessage()    {}
func (*MultiTaskOpResultRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{23}
}

func (m *MultiTaskOpResultRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiTaskOpResultRes.Unmarshal(m, b)
}
func (m *MultiTaskOpResultRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiTaskOpResultRes.Marshal(b, m, deterministic)
}
func (m *MultiTaskOpResultRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiTaskOpResultRes.Merge(m, src)
}
func (m *MultiTaskOpResultRes) XXX_Size() int {
	return xxx_messageInfo_MultiTaskOpResultRes.Size(m)
}
func (m *MultiTaskOpResultRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiTaskOpResultRes.DiscardUnknown(m)
}

var xxx_messageInfo_MultiTaskOpResultRes proto.InternalMessageInfo

func (m *MultiTaskOpResultRes) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *MultiTaskOpResultRes) GetSuccNum() int32 {
	if m != nil {
		return m.SuccNum
	}
	return 0
}

//msgid=0x4bc6
type ListDNIReq struct {
	Nextid               string   `protobuf:"bytes,1,opt,name=nextid,proto3" json:"nextid,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDNIReq) Reset()         { *m = ListDNIReq{} }
func (m *ListDNIReq) String() string { return proto.CompactTextString(m) }
func (*ListDNIReq) ProtoMessage()    {}
func (*ListDNIReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{24}
}

func (m *ListDNIReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDNIReq.Unmarshal(m, b)
}
func (m *ListDNIReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDNIReq.Marshal(b, m, deterministic)
}
func (m *ListDNIReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDNIReq.Merge(m, src)
}
func (m *ListDNIReq) XXX_Size() int {
	return xxx_messageInfo_ListDNIReq.Size(m)
}
func (m *ListDNIReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDNIReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListDNIReq proto.InternalMessageInfo

func (m *ListDNIReq) GetNextid() string {
	if m != nil {
		return m.Nextid
	}
	return ""
}

func (m *ListDNIReq) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

//msgid=0xd6cb
type ListDNIResp struct {
	Vnflist              [][]byte `protobuf:"bytes,1,rep,name=vnflist,proto3" json:"vnflist,omitempty"`
	Nextid               string   `protobuf:"bytes,2,opt,name=nextid,proto3" json:"nextid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDNIResp) Reset()         { *m = ListDNIResp{} }
func (m *ListDNIResp) String() string { return proto.CompactTextString(m) }
func (*ListDNIResp) ProtoMessage()    {}
func (*ListDNIResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{25}
}

func (m *ListDNIResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDNIResp.Unmarshal(m, b)
}
func (m *ListDNIResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDNIResp.Marshal(b, m, deterministic)
}
func (m *ListDNIResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDNIResp.Merge(m, src)
}
func (m *ListDNIResp) XXX_Size() int {
	return xxx_messageInfo_ListDNIResp.Size(m)
}
func (m *ListDNIResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDNIResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListDNIResp proto.InternalMessageInfo

func (m *ListDNIResp) GetVnflist() [][]byte {
	if m != nil {
		return m.Vnflist
	}
	return nil
}

func (m *ListDNIResp) GetNextid() string {
	if m != nil {
		return m.Nextid
	}
	return ""
}

//  本次需要校验的条数
//msgid = 0xd97a
type SelfVerifyReq struct {
	Num                  string   `protobuf:"bytes,1,opt,name=Num,proto3" json:"Num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelfVerifyReq) Reset()         { *m = SelfVerifyReq{} }
func (m *SelfVerifyReq) String() string { return proto.CompactTextString(m) }
func (*SelfVerifyReq) ProtoMessage()    {}
func (*SelfVerifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{26}
}

func (m *SelfVerifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfVerifyReq.Unmarshal(m, b)
}
func (m *SelfVerifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfVerifyReq.Marshal(b, m, deterministic)
}
func (m *SelfVerifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfVerifyReq.Merge(m, src)
}
func (m *SelfVerifyReq) XXX_Size() int {
	return xxx_messageInfo_SelfVerifyReq.Size(m)
}
func (m *SelfVerifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfVerifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_SelfVerifyReq proto.InternalMessageInfo

func (m *SelfVerifyReq) GetNum() string {
	if m != nil {
		return m.Num
	}
	return ""
}

type HashToHash struct {
	DBhash               []byte   `protobuf:"bytes,1,opt,name=DBhash,proto3" json:"DBhash,omitempty"`
	Datahash             []byte   `protobuf:"bytes,2,opt,name=Datahash,proto3" json:"Datahash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashToHash) Reset()         { *m = HashToHash{} }
func (m *HashToHash) String() string { return proto.CompactTextString(m) }
func (*HashToHash) ProtoMessage()    {}
func (*HashToHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{27}
}

func (m *HashToHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashToHash.Unmarshal(m, b)
}
func (m *HashToHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashToHash.Marshal(b, m, deterministic)
}
func (m *HashToHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashToHash.Merge(m, src)
}
func (m *HashToHash) XXX_Size() int {
	return xxx_messageInfo_HashToHash.Size(m)
}
func (m *HashToHash) XXX_DiscardUnknown() {
	xxx_messageInfo_HashToHash.DiscardUnknown(m)
}

var xxx_messageInfo_HashToHash proto.InternalMessageInfo

func (m *HashToHash) GetDBhash() []byte {
	if m != nil {
		return m.DBhash
	}
	return nil
}

func (m *HashToHash) GetDatahash() []byte {
	if m != nil {
		return m.Datahash
	}
	return nil
}

//id:矿机id，数字形式（比如：12398）
//entryth:校验的起始entry
//Num:本次校验的数目
//errNum:校验出错的分片数
//errCode:错误类型码
//errShard:错误的分片列表
//msgid = 0x58b7
type SelfVerifyResp struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Entryth              string        `protobuf:"bytes,2,opt,name=entryth,proto3" json:"entryth,omitempty"`
	Num                  string        `protobuf:"bytes,3,opt,name=Num,proto3" json:"Num,omitempty"`
	ErrNum               string        `protobuf:"bytes,4,opt,name=errNum,proto3" json:"errNum,omitempty"`
	ErrCode              string        `protobuf:"bytes,5,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrShard             []*HashToHash `protobuf:"bytes,6,rep,name=errShard,proto3" json:"errShard,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SelfVerifyResp) Reset()         { *m = SelfVerifyResp{} }
func (m *SelfVerifyResp) String() string { return proto.CompactTextString(m) }
func (*SelfVerifyResp) ProtoMessage()    {}
func (*SelfVerifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{28}
}

func (m *SelfVerifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfVerifyResp.Unmarshal(m, b)
}
func (m *SelfVerifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfVerifyResp.Marshal(b, m, deterministic)
}
func (m *SelfVerifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfVerifyResp.Merge(m, src)
}
func (m *SelfVerifyResp) XXX_Size() int {
	return xxx_messageInfo_SelfVerifyResp.Size(m)
}
func (m *SelfVerifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfVerifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_SelfVerifyResp proto.InternalMessageInfo

func (m *SelfVerifyResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SelfVerifyResp) GetEntryth() string {
	if m != nil {
		return m.Entryth
	}
	return ""
}

func (m *SelfVerifyResp) GetNum() string {
	if m != nil {
		return m.Num
	}
	return ""
}

func (m *SelfVerifyResp) GetErrNum() string {
	if m != nil {
		return m.ErrNum
	}
	return ""
}

func (m *SelfVerifyResp) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *SelfVerifyResp) GetErrShard() []*HashToHash {
	if m != nil {
		return m.ErrShard
	}
	return nil
}

//MessageID:0xe87a
type GcReq struct {
	DelPubKey            []byte   `protobuf:"bytes,1,opt,name=delPubKey,proto3" json:"delPubKey,omitempty"`
	Dnid                 uint32   `protobuf:"varint,2,opt,name=dnid,proto3" json:"dnid,omitempty"`
	TaskId               string   `protobuf:"bytes,3,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Gclist               [][]byte `protobuf:"bytes,4,rep,name=Gclist,proto3" json:"Gclist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GcReq) Reset()         { *m = GcReq{} }
func (m *GcReq) String() string { return proto.CompactTextString(m) }
func (*GcReq) ProtoMessage()    {}
func (*GcReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{29}
}

func (m *GcReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GcReq.Unmarshal(m, b)
}
func (m *GcReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GcReq.Marshal(b, m, deterministic)
}
func (m *GcReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GcReq.Merge(m, src)
}
func (m *GcReq) XXX_Size() int {
	return xxx_messageInfo_GcReq.Size(m)
}
func (m *GcReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GcReq.DiscardUnknown(m)
}

var xxx_messageInfo_GcReq proto.InternalMessageInfo

func (m *GcReq) GetDelPubKey() []byte {
	if m != nil {
		return m.DelPubKey
	}
	return nil
}

func (m *GcReq) GetDnid() uint32 {
	if m != nil {
		return m.Dnid
	}
	return 0
}

func (m *GcReq) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *GcReq) GetGclist() [][]byte {
	if m != nil {
		return m.Gclist
	}
	return nil
}

//MessageID:0xe87b
type GcResp struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Dnid                 uint32   `protobuf:"varint,2,opt,name=dnid,proto3" json:"dnid,omitempty"`
	ErrCode              string   `protobuf:"bytes,3,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GcResp) Reset()         { *m = GcResp{} }
func (m *GcResp) String() string { return proto.CompactTextString(m) }
func (*GcResp) ProtoMessage()    {}
func (*GcResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{30}
}

func (m *GcResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GcResp.Unmarshal(m, b)
}
func (m *GcResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GcResp.Marshal(b, m, deterministic)
}
func (m *GcResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GcResp.Merge(m, src)
}
func (m *GcResp) XXX_Size() int {
	return xxx_messageInfo_GcResp.Size(m)
}
func (m *GcResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GcResp.DiscardUnknown(m)
}

var xxx_messageInfo_GcResp proto.InternalMessageInfo

func (m *GcResp) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *GcResp) GetDnid() uint32 {
	if m != nil {
		return m.Dnid
	}
	return 0
}

func (m *GcResp) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

//MessageID:0xe87e
type GcStatusReq struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Dnid                 uint32   `protobuf:"varint,2,opt,name=dnid,proto3" json:"dnid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GcStatusReq) Reset()         { *m = GcStatusReq{} }
func (m *GcStatusReq) String() string { return proto.CompactTextString(m) }
func (*GcStatusReq) ProtoMessage()    {}
func (*GcStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{31}
}

func (m *GcStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GcStatusReq.Unmarshal(m, b)
}
func (m *GcStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GcStatusReq.Marshal(b, m, deterministic)
}
func (m *GcStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GcStatusReq.Merge(m, src)
}
func (m *GcStatusReq) XXX_Size() int {
	return xxx_messageInfo_GcStatusReq.Size(m)
}
func (m *GcStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GcStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_GcStatusReq proto.InternalMessageInfo

func (m *GcStatusReq) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *GcStatusReq) GetDnid() uint32 {
	if m != nil {
		return m.Dnid
	}
	return 0
}

//MessageID:0xe87f
type GcStatusResp struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Dnid                 uint32   `protobuf:"varint,2,opt,name=dnid,proto3" json:"dnid,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Total                int32    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Fail                 int32    `protobuf:"varint,5,opt,name=fail,proto3" json:"fail,omitempty"`
	Errlist              [][]byte `protobuf:"bytes,6,rep,name=errlist,proto3" json:"errlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GcStatusResp) Reset()         { *m = GcStatusResp{} }
func (m *GcStatusResp) String() string { return proto.CompactTextString(m) }
func (*GcStatusResp) ProtoMessage()    {}
func (*GcStatusResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{32}
}

func (m *GcStatusResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GcStatusResp.Unmarshal(m, b)
}
func (m *GcStatusResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GcStatusResp.Marshal(b, m, deterministic)
}
func (m *GcStatusResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GcStatusResp.Merge(m, src)
}
func (m *GcStatusResp) XXX_Size() int {
	return xxx_messageInfo_GcStatusResp.Size(m)
}
func (m *GcStatusResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GcStatusResp.DiscardUnknown(m)
}

var xxx_messageInfo_GcStatusResp proto.InternalMessageInfo

func (m *GcStatusResp) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *GcStatusResp) GetDnid() uint32 {
	if m != nil {
		return m.Dnid
	}
	return 0
}

func (m *GcStatusResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GcStatusResp) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GcStatusResp) GetFail() int32 {
	if m != nil {
		return m.Fail
	}
	return 0
}

func (m *GcStatusResp) GetErrlist() [][]byte {
	if m != nil {
		return m.Errlist
	}
	return nil
}

//MessageID:0xe88e
type GcdelStatusfileReq struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Dnid                 uint32   `protobuf:"varint,2,opt,name=dnid,proto3" json:"dnid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GcdelStatusfileReq) Reset()         { *m = GcdelStatusfileReq{} }
func (m *GcdelStatusfileReq) String() string { return proto.CompactTextString(m) }
func (*GcdelStatusfileReq) ProtoMessage()    {}
func (*GcdelStatusfileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{33}
}

func (m *GcdelStatusfileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GcdelStatusfileReq.Unmarshal(m, b)
}
func (m *GcdelStatusfileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GcdelStatusfileReq.Marshal(b, m, deterministic)
}
func (m *GcdelStatusfileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GcdelStatusfileReq.Merge(m, src)
}
func (m *GcdelStatusfileReq) XXX_Size() int {
	return xxx_messageInfo_GcdelStatusfileReq.Size(m)
}
func (m *GcdelStatusfileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GcdelStatusfileReq.DiscardUnknown(m)
}

var xxx_messageInfo_GcdelStatusfileReq proto.InternalMessageInfo

func (m *GcdelStatusfileReq) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *GcdelStatusfileReq) GetDnid() uint32 {
	if m != nil {
		return m.Dnid
	}
	return 0
}

//MessageID:0xe88f
type GcdelStatusfileResp struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Dnid                 uint32   `protobuf:"varint,2,opt,name=dnid,proto3" json:"dnid,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GcdelStatusfileResp) Reset()         { *m = GcdelStatusfileResp{} }
func (m *GcdelStatusfileResp) String() string { return proto.CompactTextString(m) }
func (*GcdelStatusfileResp) ProtoMessage()    {}
func (*GcdelStatusfileResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{34}
}

func (m *GcdelStatusfileResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GcdelStatusfileResp.Unmarshal(m, b)
}
func (m *GcdelStatusfileResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GcdelStatusfileResp.Marshal(b, m, deterministic)
}
func (m *GcdelStatusfileResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GcdelStatusfileResp.Merge(m, src)
}
func (m *GcdelStatusfileResp) XXX_Size() int {
	return xxx_messageInfo_GcdelStatusfileResp.Size(m)
}
func (m *GcdelStatusfileResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GcdelStatusfileResp.DiscardUnknown(m)
}

var xxx_messageInfo_GcdelStatusfileResp proto.InternalMessageInfo

func (m *GcdelStatusfileResp) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *GcdelStatusfileResp) GetDnid() uint32 {
	if m != nil {
		return m.Dnid
	}
	return 0
}

func (m *GcdelStatusfileResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

//MessageID:0x1b32
type DownloadYTFSFile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ServerUrl            string   `protobuf:"bytes,2,opt,name=serverUrl,proto3" json:"serverUrl,omitempty"`
	Gzip                 bool     `protobuf:"varint,3,opt,name=gzip,proto3" json:"gzip,omitempty"`
	Sig                  []byte   `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadYTFSFile) Reset()         { *m = DownloadYTFSFile{} }
func (m *DownloadYTFSFile) String() string { return proto.CompactTextString(m) }
func (*DownloadYTFSFile) ProtoMessage()    {}
func (*DownloadYTFSFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{35}
}

func (m *DownloadYTFSFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadYTFSFile.Unmarshal(m, b)
}
func (m *DownloadYTFSFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadYTFSFile.Marshal(b, m, deterministic)
}
func (m *DownloadYTFSFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadYTFSFile.Merge(m, src)
}
func (m *DownloadYTFSFile) XXX_Size() int {
	return xxx_messageInfo_DownloadYTFSFile.Size(m)
}
func (m *DownloadYTFSFile) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadYTFSFile.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadYTFSFile proto.InternalMessageInfo

func (m *DownloadYTFSFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DownloadYTFSFile) GetServerUrl() string {
	if m != nil {
		return m.ServerUrl
	}
	return ""
}

func (m *DownloadYTFSFile) GetGzip() bool {
	if m != nil {
		return m.Gzip
	}
	return false
}

func (m *DownloadYTFSFile) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

//MessageID:0x1b33
type Debug struct {
	ServerUrl            string   `protobuf:"bytes,1,opt,name=serverUrl,proto3" json:"serverUrl,omitempty"`
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Debug) Reset()         { *m = Debug{} }
func (m *Debug) String() string { return proto.CompactTextString(m) }
func (*Debug) ProtoMessage()    {}
func (*Debug) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{36}
}

func (m *Debug) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Debug.Unmarshal(m, b)
}
func (m *Debug) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Debug.Marshal(b, m, deterministic)
}
func (m *Debug) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Debug.Merge(m, src)
}
func (m *Debug) XXX_Size() int {
	return xxx_messageInfo_Debug.Size(m)
}
func (m *Debug) XXX_DiscardUnknown() {
	xxx_messageInfo_Debug.DiscardUnknown(m)
}

var xxx_messageInfo_Debug proto.InternalMessageInfo

func (m *Debug) GetServerUrl() string {
	if m != nil {
		return m.ServerUrl
	}
	return ""
}

func (m *Debug) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

//MessageID:0x1b34
type DownloadTKCheck struct {
	Tk                   string   `protobuf:"bytes,1,opt,name=tk,proto3" json:"tk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadTKCheck) Reset()         { *m = DownloadTKCheck{} }
func (m *DownloadTKCheck) String() string { return proto.CompactTextString(m) }
func (*DownloadTKCheck) ProtoMessage()    {}
func (*DownloadTKCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{37}
}

func (m *DownloadTKCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadTKCheck.Unmarshal(m, b)
}
func (m *DownloadTKCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadTKCheck.Marshal(b, m, deterministic)
}
func (m *DownloadTKCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadTKCheck.Merge(m, src)
}
func (m *DownloadTKCheck) XXX_Size() int {
	return xxx_messageInfo_DownloadTKCheck.Size(m)
}
func (m *DownloadTKCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadTKCheck.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadTKCheck proto.InternalMessageInfo

func (m *DownloadTKCheck) GetTk() string {
	if m != nil {
		return m.Tk
	}
	return ""
}

//MessageID:0xe75c
type UploadShardRequestTest struct {
	SHARDID              int32    `protobuf:"varint,1,opt,name=SHARDID,proto3" json:"SHARDID,omitempty"`
	BPDID                int32    `protobuf:"varint,2,opt,name=BPDID,proto3" json:"BPDID,omitempty"`
	VBI                  int64    `protobuf:"varint,3,opt,name=VBI,proto3" json:"VBI,omitempty"`
	BPDSIGN              []byte   `protobuf:"bytes,4,opt,name=BPDSIGN,proto3" json:"BPDSIGN,omitempty"`
	DAT                  []byte   `protobuf:"bytes,5,opt,name=DAT,proto3" json:"DAT,omitempty"`
	VHF                  []byte   `protobuf:"bytes,6,opt,name=VHF,proto3" json:"VHF,omitempty"`
	USERSIGN             []byte   `protobuf:"bytes,7,opt,name=USERSIGN,proto3" json:"USERSIGN,omitempty"`
	AllocId              string   `protobuf:"bytes,8,opt,name=allocId,proto3" json:"allocId,omitempty"`
	Sleep                uint32   `protobuf:"varint,9,opt,name=Sleep,proto3" json:"Sleep,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadShardRequestTest) Reset()         { *m = UploadShardRequestTest{} }
func (m *UploadShardRequestTest) String() string { return proto.CompactTextString(m) }
func (*UploadShardRequestTest) ProtoMessage()    {}
func (*UploadShardRequestTest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{38}
}

func (m *UploadShardRequestTest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadShardRequestTest.Unmarshal(m, b)
}
func (m *UploadShardRequestTest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadShardRequestTest.Marshal(b, m, deterministic)
}
func (m *UploadShardRequestTest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadShardRequestTest.Merge(m, src)
}
func (m *UploadShardRequestTest) XXX_Size() int {
	return xxx_messageInfo_UploadShardRequestTest.Size(m)
}
func (m *UploadShardRequestTest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadShardRequestTest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadShardRequestTest proto.InternalMessageInfo

func (m *UploadShardRequestTest) GetSHARDID() int32 {
	if m != nil {
		return m.SHARDID
	}
	return 0
}

func (m *UploadShardRequestTest) GetBPDID() int32 {
	if m != nil {
		return m.BPDID
	}
	return 0
}

func (m *UploadShardRequestTest) GetVBI() int64 {
	if m != nil {
		return m.VBI
	}
	return 0
}

func (m *UploadShardRequestTest) GetBPDSIGN() []byte {
	if m != nil {
		return m.BPDSIGN
	}
	return nil
}

func (m *UploadShardRequestTest) GetDAT() []byte {
	if m != nil {
		return m.DAT
	}
	return nil
}

func (m *UploadShardRequestTest) GetVHF() []byte {
	if m != nil {
		return m.VHF
	}
	return nil
}

func (m *UploadShardRequestTest) GetUSERSIGN() []byte {
	if m != nil {
		return m.USERSIGN
	}
	return nil
}

func (m *UploadShardRequestTest) GetAllocId() string {
	if m != nil {
		return m.AllocId
	}
	return ""
}

func (m *UploadShardRequestTest) GetSleep() uint32 {
	if m != nil {
		return m.Sleep
	}
	return 0
}

//MessageID:0xe76a  测试任务消息
type TestMinerPerfTask struct {
	TargetMa             []string `protobuf:"bytes,1,rep,name=targetMa,proto3" json:"targetMa,omitempty"`
	TestType             int32    `protobuf:"varint,2,opt,name=testType,proto3" json:"testType,omitempty"`
	TestTime             int64    `protobuf:"varint,3,opt,name=testTime,proto3" json:"testTime,omitempty"`
	TimeOut              int64    `protobuf:"varint,4,opt,name=timeOut,proto3" json:"timeOut,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMinerPerfTask) Reset()         { *m = TestMinerPerfTask{} }
func (m *TestMinerPerfTask) String() string { return proto.CompactTextString(m) }
func (*TestMinerPerfTask) ProtoMessage()    {}
func (*TestMinerPerfTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{39}
}

func (m *TestMinerPerfTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMinerPerfTask.Unmarshal(m, b)
}
func (m *TestMinerPerfTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMinerPerfTask.Marshal(b, m, deterministic)
}
func (m *TestMinerPerfTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMinerPerfTask.Merge(m, src)
}
func (m *TestMinerPerfTask) XXX_Size() int {
	return xxx_messageInfo_TestMinerPerfTask.Size(m)
}
func (m *TestMinerPerfTask) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMinerPerfTask.DiscardUnknown(m)
}

var xxx_messageInfo_TestMinerPerfTask proto.InternalMessageInfo

func (m *TestMinerPerfTask) GetTargetMa() []string {
	if m != nil {
		return m.TargetMa
	}
	return nil
}

func (m *TestMinerPerfTask) GetTestType() int32 {
	if m != nil {
		return m.TestType
	}
	return 0
}

func (m *TestMinerPerfTask) GetTestTime() int64 {
	if m != nil {
		return m.TestTime
	}
	return 0
}

func (m *TestMinerPerfTask) GetTimeOut() int64 {
	if m != nil {
		return m.TimeOut
	}
	return 0
}

//MessageID:0xe76b
type TestGetBlock struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Pld                  []byte   `protobuf:"bytes,2,opt,name=pld,proto3" json:"pld,omitempty"`
	AllocID              string   `protobuf:"bytes,3,opt,name=allocID,proto3" json:"allocID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestGetBlock) Reset()         { *m = TestGetBlock{} }
func (m *TestGetBlock) String() string { return proto.CompactTextString(m) }
func (*TestGetBlock) ProtoMessage()    {}
func (*TestGetBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{40}
}

func (m *TestGetBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestGetBlock.Unmarshal(m, b)
}
func (m *TestGetBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestGetBlock.Marshal(b, m, deterministic)
}
func (m *TestGetBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestGetBlock.Merge(m, src)
}
func (m *TestGetBlock) XXX_Size() int {
	return xxx_messageInfo_TestGetBlock.Size(m)
}
func (m *TestGetBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_TestGetBlock.DiscardUnknown(m)
}

var xxx_messageInfo_TestGetBlock proto.InternalMessageInfo

func (m *TestGetBlock) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *TestGetBlock) GetPld() []byte {
	if m != nil {
		return m.Pld
	}
	return nil
}

func (m *TestGetBlock) GetAllocID() string {
	if m != nil {
		return m.AllocID
	}
	return ""
}

//MessageID:0xe76c
type TestGetBlockRes struct {
	Msg                  []byte   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestGetBlockRes) Reset()         { *m = TestGetBlockRes{} }
func (m *TestGetBlockRes) String() string { return proto.CompactTextString(m) }
func (*TestGetBlockRes) ProtoMessage()    {}
func (*TestGetBlockRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{41}
}

func (m *TestGetBlockRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestGetBlockRes.Unmarshal(m, b)
}
func (m *TestGetBlockRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestGetBlockRes.Marshal(b, m, deterministic)
}
func (m *TestGetBlockRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestGetBlockRes.Merge(m, src)
}
func (m *TestGetBlockRes) XXX_Size() int {
	return xxx_messageInfo_TestGetBlockRes.Size(m)
}
func (m *TestGetBlockRes) XXX_DiscardUnknown() {
	xxx_messageInfo_TestGetBlockRes.DiscardUnknown(m)
}

var xxx_messageInfo_TestGetBlockRes proto.InternalMessageInfo

func (m *TestGetBlockRes) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

//MessageID:0xe76d 测试任务返回
type TestMinerPerfTaskRes struct {
	TargetMa             []string `protobuf:"bytes,1,rep,name=targetMa,proto3" json:"targetMa,omitempty"`
	TestType             int32    `protobuf:"varint,2,opt,name=testType,proto3" json:"testType,omitempty"`
	SuccessCount         int64    `protobuf:"varint,3,opt,name=successCount,proto3" json:"successCount,omitempty"`
	ErrorCount           int64    `protobuf:"varint,4,opt,name=errorCount,proto3" json:"errorCount,omitempty"`
	SuccessLatency       int64    `protobuf:"varint,5,opt,name=successLatency,proto3" json:"successLatency,omitempty"`
	ErrorLatency         int64    `protobuf:"varint,6,opt,name=errorLatency,proto3" json:"errorLatency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMinerPerfTaskRes) Reset()         { *m = TestMinerPerfTaskRes{} }
func (m *TestMinerPerfTaskRes) String() string { return proto.CompactTextString(m) }
func (*TestMinerPerfTaskRes) ProtoMessage()    {}
func (*TestMinerPerfTaskRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{42}
}

func (m *TestMinerPerfTaskRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMinerPerfTaskRes.Unmarshal(m, b)
}
func (m *TestMinerPerfTaskRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMinerPerfTaskRes.Marshal(b, m, deterministic)
}
func (m *TestMinerPerfTaskRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMinerPerfTaskRes.Merge(m, src)
}
func (m *TestMinerPerfTaskRes) XXX_Size() int {
	return xxx_messageInfo_TestMinerPerfTaskRes.Size(m)
}
func (m *TestMinerPerfTaskRes) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMinerPerfTaskRes.DiscardUnknown(m)
}

var xxx_messageInfo_TestMinerPerfTaskRes proto.InternalMessageInfo

func (m *TestMinerPerfTaskRes) GetTargetMa() []string {
	if m != nil {
		return m.TargetMa
	}
	return nil
}

func (m *TestMinerPerfTaskRes) GetTestType() int32 {
	if m != nil {
		return m.TestType
	}
	return 0
}

func (m *TestMinerPerfTaskRes) GetSuccessCount() int64 {
	if m != nil {
		return m.SuccessCount
	}
	return 0
}

func (m *TestMinerPerfTaskRes) GetErrorCount() int64 {
	if m != nil {
		return m.ErrorCount
	}
	return 0
}

func (m *TestMinerPerfTaskRes) GetSuccessLatency() int64 {
	if m != nil {
		return m.SuccessLatency
	}
	return 0
}

func (m *TestMinerPerfTaskRes) GetErrorLatency() int64 {
	if m != nil {
		return m.ErrorLatency
	}
	return 0
}

func init() {
	proto.RegisterType((*NodeCapacityRequest)(nil), "message.NodeCapacityRequest")
	proto.RegisterType((*NodeCapacityResponse)(nil), "message.NodeCapacityResponse")
	proto.RegisterType((*UploadShardRequest)(nil), "message.UploadShardRequest")
	proto.RegisterType((*UploadShardResponse)(nil), "message.UploadShardResponse")
	proto.RegisterType((*UploadShard2CResponse)(nil), "message.UploadShard2CResponse")
	proto.RegisterType((*DownloadShardRequest)(nil), "message.DownloadShardRequest")
	proto.RegisterType((*DownloadShardResponse)(nil), "message.DownloadShardResponse")
	proto.RegisterType((*NodeRegReq)(nil), "message.NodeRegReq")
	proto.RegisterType((*NodeRegResp)(nil), "message.NodeRegResp")
	proto.RegisterType((*StatusRepReq)(nil), "message.StatusRepReq")
	proto.RegisterType((*StatusRepResp)(nil), "message.StatusRepResp")
	proto.RegisterType((*ErrorMessage)(nil), "message.ErrorMessage")
	proto.RegisterType((*StringMsg)(nil), "message.StringMsg")
	proto.RegisterType((*SpotCheckTaskList)(nil), "message.SpotCheckTaskList")
	proto.RegisterType((*SpotCheckTask)(nil), "message.SpotCheckTask")
	proto.RegisterType((*SpotCheckStatus)(nil), "message.SpotCheckStatus")
	proto.RegisterType((*TaskDescription)(nil), "message.TaskDescription")
	proto.RegisterType((*TaskDescriptionCP)(nil), "message.TaskDescriptionCP")
	proto.RegisterType((*P2PLocation)(nil), "message.P2PLocation")
	proto.RegisterType((*VoidResponse)(nil), "message.VoidResponse")
	proto.RegisterType((*TaskOpResult)(nil), "message.TaskOpResult")
	proto.RegisterType((*MultiTaskDescription)(nil), "message.MultiTaskDescription")
	proto.RegisterType((*MultiTaskOpResult)(nil), "message.MultiTaskOpResult")
	proto.RegisterType((*MultiTaskOpResultRes)(nil), "message.MultiTaskOpResultRes")
	proto.RegisterType((*ListDNIReq)(nil), "message.ListDNIReq")
	proto.RegisterType((*ListDNIResp)(nil), "message.ListDNIResp")
	proto.RegisterType((*SelfVerifyReq)(nil), "message.SelfVerifyReq")
	proto.RegisterType((*HashToHash)(nil), "message.HashToHash")
	proto.RegisterType((*SelfVerifyResp)(nil), "message.SelfVerifyResp")
	proto.RegisterType((*GcReq)(nil), "message.GcReq")
	proto.RegisterType((*GcResp)(nil), "message.GcResp")
	proto.RegisterType((*GcStatusReq)(nil), "message.GcStatusReq")
	proto.RegisterType((*GcStatusResp)(nil), "message.GcStatusResp")
	proto.RegisterType((*GcdelStatusfileReq)(nil), "message.GcdelStatusfileReq")
	proto.RegisterType((*GcdelStatusfileResp)(nil), "message.GcdelStatusfileResp")
	proto.RegisterType((*DownloadYTFSFile)(nil), "message.DownloadYTFSFile")
	proto.RegisterType((*Debug)(nil), "message.Debug")
	proto.RegisterType((*DownloadTKCheck)(nil), "message.DownloadTKCheck")
	proto.RegisterType((*UploadShardRequestTest)(nil), "message.UploadShardRequestTest")
	proto.RegisterType((*TestMinerPerfTask)(nil), "message.TestMinerPerfTask")
	proto.RegisterType((*TestGetBlock)(nil), "message.TestGetBlock")
	proto.RegisterType((*TestGetBlockRes)(nil), "message.TestGetBlockRes")
	proto.RegisterType((*TestMinerPerfTaskRes)(nil), "message.TestMinerPerfTaskRes")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 1662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0x4f, 0x6f, 0x23, 0x49,
	0x15, 0x57, 0xbb, 0x6d, 0xc7, 0x7e, 0xb1, 0x93, 0x4c, 0x4f, 0x36, 0x6a, 0x8d, 0x06, 0xe4, 0x2d,
	0x10, 0xb2, 0x40, 0x5a, 0x50, 0x40, 0x42, 0x0b, 0x07, 0x76, 0x13, 0xcf, 0x64, 0xcc, 0x26, 0x99,
	0xa8, 0x9c, 0x44, 0xda, 0x03, 0x42, 0x9d, 0xee, 0x8a, 0xd3, 0xa4, 0xdd, 0xdd, 0xa9, 0x2a, 0xe7,
	0x0f, 0x37, 0xae, 0x48, 0x5c, 0x39, 0xf1, 0x1d, 0xb8, 0xc0, 0x97, 0xe0, 0x43, 0x70, 0xe2, 0x83,
	0xa0, 0xf7, 0xaa, 0xfa, 0x9f, 0x9d, 0x5d, 0x34, 0x23, 0x2e, 0x7b, 0xab, 0xdf, 0xeb, 0xaa, 0x57,
	0xbf, 0xf7, 0xaf, 0xde, 0xb3, 0x61, 0xb8, 0x10, 0x4a, 0x05, 0x73, 0xf1, 0x59, 0x2e, 0x33, 0x9d,
	0x79, 0x1b, 0x16, 0xb2, 0xcf, 0xe1, 0xe5, 0x69, 0x16, 0x89, 0xc3, 0x20, 0x0f, 0xc2, 0x58, 0x3f,
	0x71, 0x71, 0xb7, 0x14, 0x4a, 0x7b, 0x0c, 0x06, 0x76, 0x79, 0xa2, 0xe6, 0xd3, 0x89, 0xef, 0x8c,
	0x9c, 0x71, 0x87, 0x37, 0x64, 0xec, 0x18, 0x76, 0x9b, 0x47, 0x55, 0x9e, 0xa5, 0x4a, 0x78, 0xaf,
	0xa0, 0xf7, 0x20, 0x63, 0x1d, 0x5c, 0x25, 0x82, 0xce, 0xf5, 0x78, 0x89, 0x3d, 0x1f, 0x36, 0x82,
	0x24, 0xc9, 0xc2, 0x69, 0xe4, 0xb7, 0x46, 0xce, 0xb8, 0xcf, 0x0b, 0xc8, 0xfe, 0xe5, 0x80, 0x77,
	0x91, 0x27, 0x59, 0x10, 0xcd, 0x6e, 0x02, 0x19, 0x15, 0x44, 0x7c, 0xd8, 0x98, 0xbd, 0xfb, 0x92,
	0x4f, 0x4a, 0x0e, 0x05, 0xf4, 0x76, 0xa1, 0x73, 0x70, 0x86, 0xf2, 0x16, 0xc9, 0x0d, 0xf0, 0x76,
	0xc0, 0xbd, 0x3c, 0x98, 0xfa, 0xee, 0xc8, 0x19, 0xbb, 0x1c, 0x97, 0xa8, 0xe1, 0xe0, 0x6c, 0x32,
	0x9b, 0x1e, 0x9d, 0xfa, 0xed, 0x91, 0x33, 0x1e, 0xf0, 0x02, 0xe2, 0xde, 0xc9, 0x97, 0xe7, 0x7e,
	0x87, 0xa4, 0xb8, 0xa4, 0xd3, 0xef, 0xde, 0xfa, 0x5d, 0x23, 0xb9, 0x7c, 0xf7, 0x16, 0x8d, 0xb9,
	0x98, 0xbd, 0xe1, 0x74, 0x7c, 0x83, 0xc4, 0x25, 0xae, 0x1b, 0xd3, 0x6b, 0x1a, 0xf3, 0x27, 0x07,
	0x5e, 0x36, 0x8c, 0xb1, 0xae, 0xd9, 0x01, 0x97, 0xbf, 0x99, 0x59, 0x4b, 0x70, 0x59, 0xb7, 0xaf,
	0xd5, 0xb4, 0x6f, 0xdd, 0x12, 0xcb, 0xae, 0xfd, 0x3c, 0xbb, 0x4e, 0x93, 0x1d, 0x9b, 0xc3, 0x27,
	0x35, 0x0a, 0xfb, 0x87, 0xdf, 0x42, 0x62, 0x0f, 0xba, 0x93, 0x53, 0x52, 0x62, 0x82, 0x62, 0x11,
	0xee, 0x54, 0xe2, 0xae, 0xa0, 0xa0, 0xc4, 0x9d, 0xe7, 0x41, 0xfb, 0x26, 0x50, 0x37, 0x96, 0x03,
	0xad, 0xd9, 0x01, 0xec, 0x4e, 0xb2, 0x87, 0x74, 0x2d, 0x74, 0x96, 0xae, 0x53, 0xd1, 0xfd, 0xe6,
	0xe8, 0xff, 0x04, 0x3e, 0x59, 0xd1, 0x61, 0xc9, 0x7a, 0xd0, 0x8e, 0x02, 0x1d, 0x58, 0x2d, 0xb4,
	0x66, 0x7f, 0x76, 0x00, 0x30, 0xf3, 0xb8, 0x98, 0x73, 0x71, 0x87, 0xec, 0xd3, 0x2c, 0x12, 0x71,
	0x44, 0x9b, 0xfa, 0xdc, 0x22, 0x4c, 0x90, 0xec, 0x21, 0x15, 0xd2, 0xde, 0x65, 0x00, 0x66, 0xf6,
	0x22, 0x78, 0x9c, 0x04, 0x3a, 0x98, 0xe5, 0x41, 0x28, 0xc8, 0xb8, 0x36, 0x6f, 0xc8, 0xf0, 0x64,
	0x10, 0x45, 0x52, 0xf9, 0xed, 0x91, 0x8b, 0x27, 0x09, 0xa0, 0x54, 0x8a, 0x24, 0x78, 0x22, 0x4f,
	0xf7, 0xb8, 0x01, 0xec, 0xf7, 0xb0, 0x59, 0x72, 0x51, 0xb9, 0xb7, 0x05, 0x2d, 0x4b, 0x64, 0xc8,
	0x5b, 0x71, 0xe4, 0xfd, 0x10, 0x86, 0x81, 0x52, 0xf1, 0x3c, 0x15, 0x91, 0xb9, 0xaf, 0x45, 0xf7,
	0x35, 0x85, 0x18, 0x47, 0xd2, 0x76, 0x21, 0x13, 0x22, 0xd4, 0xe7, 0x25, 0x66, 0x7f, 0x73, 0x61,
	0x30, 0xd3, 0x81, 0x5e, 0x2a, 0x2e, 0x72, 0xb4, 0x77, 0xf5, 0x8a, 0x1d, 0x70, 0xc3, 0x7c, 0x49,
	0x8a, 0x87, 0x1c, 0x97, 0xe8, 0x91, 0x85, 0x58, 0x64, 0xf2, 0x89, 0x94, 0x0d, 0xb9, 0x45, 0xde,
	0x6b, 0xe8, 0x5f, 0x05, 0x69, 0xf4, 0x10, 0x47, 0xda, 0x84, 0x70, 0xc8, 0x2b, 0xc1, 0x9a, 0x67,
	0x3a, 0xcf, 0x78, 0x66, 0xcd, 0x9c, 0xee, 0x73, 0xe6, 0xbc, 0x86, 0xfe, 0x52, 0x15, 0x3b, 0x36,
	0x68, 0x47, 0x25, 0xa8, 0xbc, 0xdb, 0x7b, 0xd6, 0xbb, 0xfd, 0x9a, 0x77, 0x31, 0x63, 0xee, 0x85,
	0x54, 0x71, 0x96, 0xfa, 0x40, 0x7c, 0x0b, 0xe8, 0x7d, 0x1f, 0x40, 0x8a, 0xab, 0x65, 0x9c, 0x44,
	0x71, 0x3a, 0xf7, 0x37, 0xe9, 0x63, 0x4d, 0x82, 0x1c, 0xa4, 0x08, 0x12, 0xc3, 0x61, 0x60, 0x6c,
	0x2d, 0x05, 0xe8, 0x43, 0xfd, 0xe8, 0x0f, 0x89, 0x5a, 0x4b, 0x3f, 0x22, 0x96, 0x8f, 0xfe, 0x96,
	0xc1, 0xf2, 0x11, 0xd9, 0xbc, 0xd7, 0x37, 0x42, 0xfa, 0xdb, 0x26, 0x77, 0x08, 0x94, 0xd9, 0xbf,
	0x43, 0x42, 0x93, 0xfd, 0x17, 0x30, 0xac, 0x45, 0x47, 0xe5, 0xde, 0x18, 0xb6, 0x73, 0x99, 0x45,
	0xcb, 0x50, 0xc7, 0xf7, 0xc2, 0x5c, 0xef, 0x50, 0x01, 0xad, 0x8a, 0x1b, 0x51, 0x6f, 0xad, 0x44,
	0xfd, 0x17, 0x30, 0x78, 0x23, 0x65, 0x26, 0x4f, 0xcc, 0x3b, 0x8d, 0x57, 0x87, 0x59, 0x24, 0x6c,
	0xd5, 0xd2, 0x1a, 0x03, 0xbf, 0x50, 0x73, 0x7b, 0x14, 0x97, 0xec, 0x7b, 0xd0, 0x9f, 0x69, 0x19,
	0xa7, 0xf3, 0x13, 0x35, 0x2f, 0x3e, 0x3b, 0xd5, 0xe7, 0xbf, 0x38, 0xf0, 0x62, 0x96, 0x67, 0xfa,
	0xf0, 0x46, 0x84, 0xb7, 0xe7, 0x81, 0xba, 0x3d, 0x8e, 0x95, 0xc6, 0x6c, 0xd1, 0x81, 0xba, 0x9d,
	0x96, 0xf5, 0x63, 0x10, 0x5e, 0xa9, 0xd2, 0x38, 0xb2, 0xef, 0x12, 0xad, 0xbd, 0x7d, 0xe8, 0x69,
	0x7b, 0xce, 0x77, 0x47, 0xee, 0x78, 0x73, 0x7f, 0xef, 0xb3, 0xa2, 0xb3, 0x34, 0x34, 0xf3, 0x72,
	0x5f, 0xbd, 0xea, 0xdb, 0xcd, 0xaa, 0xff, 0x1d, 0x0c, 0x1b, 0x87, 0x6a, 0xa9, 0xdd, 0xa1, 0xd4,
	0xb6, 0xa5, 0x5d, 0xbe, 0x17, 0x16, 0x21, 0x35, 0xcc, 0x1a, 0x5b, 0x2b, 0xb4, 0x5e, 0x7f, 0x1d,
	0xd9, 0x0c, 0xb6, 0x4b, 0xf5, 0x26, 0x46, 0xdf, 0x68, 0xeb, 0x18, 0xb6, 0xe3, 0xf4, 0x3e, 0x48,
	0xe2, 0x08, 0x8b, 0x99, 0xcc, 0x6b, 0x8d, 0xdc, 0x71, 0x87, 0xaf, 0x8a, 0xd9, 0x3f, 0x1d, 0xd8,
	0x46, 0xae, 0x13, 0xa1, 0x42, 0x19, 0xe7, 0x1a, 0x73, 0xb1, 0xa2, 0x3d, 0x20, 0xda, 0xbb, 0xd0,
	0xc1, 0xdc, 0x50, 0xa4, 0x63, 0xc0, 0x0d, 0xf0, 0xf6, 0xa1, 0x9f, 0x64, 0x61, 0x80, 0x27, 0x94,
	0x75, 0xde, 0x6e, 0xe9, 0xbc, 0xb3, 0xfd, 0xb3, 0x63, 0xfb, 0x91, 0x57, 0xdb, 0xbc, 0x1f, 0xc3,
	0x4e, 0x1e, 0xc8, 0x58, 0x3f, 0xd1, 0xab, 0x78, 0x98, 0x2d, 0x53, 0x4d, 0x16, 0x76, 0xf8, 0x9a,
	0xdc, 0x64, 0x7c, 0x98, 0xdd, 0x0b, 0x39, 0x8d, 0xa8, 0x78, 0x3b, 0xbc, 0x12, 0x30, 0x05, 0x2f,
	0x56, 0x68, 0x1f, 0x9e, 0xad, 0x11, 0x7f, 0x05, 0x3d, 0x7c, 0x61, 0xdf, 0x61, 0x92, 0xb7, 0x4c,
	0x3f, 0x29, 0xf0, 0xc7, 0xd0, 0x67, 0xbf, 0x86, 0xcd, 0xda, 0x97, 0x5a, 0x38, 0x9d, 0x46, 0x38,
	0xcb, 0x17, 0xa1, 0x55, 0x7b, 0x11, 0xd8, 0x16, 0x0c, 0x2e, 0xb3, 0xb8, 0x6c, 0x05, 0xec, 0x67,
	0x30, 0x40, 0x0b, 0xde, 0x63, 0x99, 0x2d, 0x13, 0xbd, 0x46, 0xde, 0xf6, 0xb5, 0x56, 0xd9, 0xd7,
	0xd8, 0x3f, 0x1c, 0xd8, 0x3d, 0x59, 0x26, 0x3a, 0x5e, 0x0d, 0xd8, 0x2b, 0x93, 0xc6, 0x09, 0xc6,
	0xd9, 0xa1, 0x18, 0x95, 0xd8, 0x1b, 0xc1, 0xa6, 0x78, 0xcc, 0x63, 0x29, 0xa2, 0xf3, 0x78, 0x61,
	0xde, 0x6b, 0x97, 0xd7, 0x45, 0xe8, 0x68, 0x25, 0x43, 0xcc, 0x88, 0xe9, 0x84, 0x52, 0xb0, 0xc3,
	0x2b, 0x81, 0xf7, 0x23, 0xd8, 0xaa, 0x6d, 0x3e, 0x0a, 0x72, 0x1b, 0xb0, 0x15, 0x69, 0xbd, 0x2c,
	0x3a, 0xcd, 0xb2, 0xc0, 0x32, 0x2d, 0x69, 0xaf, 0x99, 0xeb, 0xae, 0x9a, 0xeb, 0xd6, 0xda, 0x78,
	0x83, 0x94, 0x45, 0xab, 0x16, 0xb5, 0xff, 0x87, 0x45, 0x9d, 0x15, 0x8b, 0xd8, 0x6f, 0x6b, 0x5e,
	0x2c, 0xe8, 0x70, 0xa1, 0xd0, 0x02, 0x21, 0xe5, 0x61, 0xf5, 0x2c, 0x15, 0x90, 0xa6, 0x9a, 0x65,
	0x18, 0x9e, 0x2e, 0x17, 0xe5, 0x54, 0x63, 0x20, 0xfb, 0x15, 0x00, 0x96, 0xd1, 0xe4, 0x74, 0x5a,
	0xb4, 0x6e, 0xf1, 0xa8, 0x6b, 0xad, 0x9b, 0x10, 0x26, 0x44, 0x48, 0xb9, 0x6e, 0x67, 0x3b, 0x02,
	0xec, 0x37, 0xb0, 0x59, 0x9e, 0x55, 0xe4, 0xc0, 0xfb, 0xf4, 0xba, 0x16, 0xc3, 0x02, 0xd6, 0xd4,
	0xb6, 0xea, 0x6a, 0xd9, 0xa7, 0x30, 0x9c, 0x89, 0xe4, 0xfa, 0x52, 0xc8, 0xf8, 0x1a, 0x47, 0x5d,
	0xf4, 0x21, 0x72, 0xb4, 0x4f, 0x24, 0xf2, 0xfb, 0x02, 0x00, 0xb3, 0xfd, 0x3c, 0xa3, 0x9c, 0xc7,
	0xc1, 0xe8, 0x80, 0x9e, 0x7c, 0x93, 0x66, 0x16, 0x61, 0xfe, 0x60, 0x4f, 0xbc, 0xa9, 0xd5, 0x49,
	0x81, 0xd9, 0xdf, 0x1d, 0xd8, 0xaa, 0xdf, 0xd2, 0x18, 0x0a, 0xfa, 0x14, 0x3a, 0x74, 0x5c, 0xaa,
	0xe5, 0x93, 0xbe, 0x29, 0xe6, 0x20, 0x0b, 0x0b, 0x42, 0x6e, 0x49, 0x08, 0x29, 0x08, 0x29, 0x51,
	0x68, 0x1e, 0x4f, 0x8b, 0xea, 0xce, 0xb7, 0xe9, 0x53, 0x38, 0xff, 0xa7, 0xd0, 0x13, 0x52, 0xd2,
	0xc3, 0xe0, 0x77, 0xa9, 0x4e, 0x5f, 0x96, 0x75, 0x5a, 0xd9, 0xc6, 0xcb, 0x4d, 0x2c, 0x86, 0xce,
	0x51, 0x88, 0xee, 0x78, 0x0d, 0xfd, 0x48, 0x24, 0x67, 0xcb, 0xab, 0xaf, 0xc4, 0x93, 0xb5, 0xb8,
	0x12, 0xd0, 0x28, 0x56, 0xf4, 0x83, 0x21, 0xa7, 0x75, 0xed, 0x3d, 0x75, 0x1b, 0xef, 0xe9, 0x1e,
	0x74, 0x8f, 0x42, 0x0a, 0x4d, 0x9b, 0x42, 0x63, 0x11, 0x3b, 0x45, 0x39, 0xf9, 0xe4, 0x5b, 0xba,
	0xce, 0xda, 0x2d, 0x3e, 0x6c, 0xbc, 0xb1, 0xb6, 0x9a, 0x6b, 0x0a, 0xc8, 0x3e, 0x87, 0xcd, 0xa3,
	0xb0, 0xe8, 0xbf, 0x77, 0x1f, 0xa2, 0x94, 0xfd, 0xd5, 0x81, 0x41, 0x75, 0xf6, 0x03, 0x19, 0xed,
	0x41, 0x57, 0xd1, 0xc9, 0xc2, 0x6e, 0x83, 0x30, 0x71, 0x75, 0xa6, 0x83, 0xc4, 0xd6, 0xbc, 0x01,
	0xa8, 0xe1, 0x3a, 0x88, 0x13, 0x5b, 0x59, 0xb4, 0xb6, 0xf1, 0x23, 0x17, 0x75, 0x4d, 0xf6, 0x5a,
	0xc8, 0xbe, 0x00, 0xef, 0x28, 0x8c, 0x44, 0x62, 0xa8, 0x5d, 0xc7, 0x89, 0xf8, 0x50, 0xd3, 0xbe,
	0x86, 0x97, 0x6b, 0x1a, 0xfe, 0x3f, 0x06, 0xb2, 0x3f, 0xc0, 0x4e, 0x31, 0xa8, 0x7f, 0x7d, 0xfe,
	0x76, 0xf6, 0x36, 0x4e, 0x68, 0x36, 0x49, 0x83, 0x85, 0xb0, 0x5a, 0x69, 0x4d, 0x2f, 0x8a, 0x90,
	0xf7, 0x42, 0x56, 0xc3, 0x4d, 0x25, 0xc0, 0x13, 0xf3, 0x3f, 0xc6, 0x39, 0xe9, 0xee, 0x71, 0x5a,
	0xd3, 0x8f, 0x8d, 0x78, 0x5e, 0xf4, 0x6f, 0x15, 0xcf, 0xd9, 0x2f, 0xa1, 0x33, 0x11, 0x57, 0xcb,
	0x79, 0x53, 0x99, 0xb3, 0xaa, 0xcc, 0x1e, 0x6c, 0x55, 0x07, 0x3f, 0x85, 0xed, 0x82, 0xe4, 0xf9,
	0x57, 0xd4, 0xfe, 0x69, 0xe0, 0xbb, 0x2d, 0x4a, 0x50, 0xdf, 0xb2, 0xff, 0x38, 0xb0, 0xb7, 0xfe,
	0x73, 0xf3, 0xfc, 0x3b, 0xfb, 0x93, 0x13, 0xb9, 0xcd, 0x12, 0x21, 0x72, 0x9a, 0x9f, 0x87, 0xdc,
	0x00, 0xfc, 0x21, 0xfa, 0x02, 0x8d, 0x3a, 0x89, 0x53, 0x21, 0xcf, 0x84, 0xbc, 0xa6, 0x31, 0x8b,
	0xda, 0x9f, 0x9c, 0x0b, 0x7d, 0x12, 0xd0, 0xd3, 0xd9, 0xe7, 0x25, 0xa6, 0x6f, 0xe8, 0x89, 0xa7,
	0x5c, 0x58, 0x33, 0x4b, 0x5c, 0x7e, 0xc3, 0x2e, 0x62, 0xcc, 0x2d, 0x31, 0x32, 0xd3, 0xf1, 0x42,
	0xbc, 0x5f, 0x6a, 0xdb, 0x60, 0x0a, 0xc8, 0x8e, 0x61, 0x80, 0x14, 0x8e, 0x84, 0x3e, 0x48, 0xb2,
	0xf0, 0x76, 0x7d, 0x2e, 0x45, 0x49, 0x9e, 0x44, 0x45, 0x04, 0xf3, 0x24, 0xaa, 0xec, 0x9c, 0x14,
	0x15, 0x6f, 0x21, 0xfb, 0x01, 0x6c, 0xd7, 0xb5, 0x61, 0x1f, 0xaa, 0x29, 0x1c, 0x98, 0x41, 0xf7,
	0xdf, 0x0e, 0xec, 0xae, 0x99, 0x8d, 0x5b, 0x3f, 0xd6, 0x72, 0x06, 0x03, 0xb5, 0x0c, 0x43, 0xa1,
	0x94, 0x99, 0xc1, 0x8c, 0xf5, 0x0d, 0x19, 0xfe, 0x22, 0x11, 0x38, 0xb2, 0x57, 0x53, 0x9a, 0xcb,
	0x6b, 0x12, 0x1c, 0x0c, 0xec, 0xfe, 0xe3, 0x40, 0x8b, 0x34, 0x34, 0x3f, 0x24, 0x5d, 0xbe, 0x22,
	0xc5, 0xbb, 0xe8, 0x54, 0xb1, 0xab, 0x6b, 0xee, 0xaa, 0xcb, 0xae, 0xba, 0xf4, 0x37, 0xce, 0xcf,
	0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x18, 0x5d, 0xd7, 0xf7, 0xd7, 0x11, 0x00, 0x00,
}
